spring:
  profiles:
    active: @spring.profile.active@
  data:
    rest:
      base-path: /api
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
  http:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB